logging.pattern.console=%d{HH:mm:ss} [%thread] [correlationId=%X{correlationId}] %-5level %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always