spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  use-management-port: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: "clé-très-très-très-très-très-très-très-secrète"
  expiration: 3600000